services:
  client:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    networks:
      - graduation_network

  admin:
    build: ./admin
    ports:
      - "3001:3001"
    volumes:
      - ./admin:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    depends_on:
      - api
    networks:
      - graduation_network

  api:
    build: ./api
    ports:
      - "5000:5000"
    volumes:
      - ./api:/app
      - /app/node_modules
    environment:
      - CHOKIDAR_USEPOLLING=true
    networks:
      - graduation_network

  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: ai
    ports:
      - "8003:8003"
    volumes:
      - ./ai:/app
    environment:
      - BACKEND_API_URL=http://api:5000
    depends_on:
      - api
    networks:
      - graduation_network

networks:
  graduation_network:
    driver: bridge
